docs-web/src/main/webapp/src/locale/de.json

Trying to contribute a bit, even without Java knowledge :)

Update some German translations

---

docs-web/src/main/webapp/src/locale/de.json

Fixed some typos, changed grammar to sound little more native, added a few words here and there to avoid potential ambiguities.

 Fixed typos, grammar and meaning in German translation

---

README.md

Added DOCS_BASE_URL to the environment variables as without it you won't be able to follow the link in the email.

Added required environment variable to startup

---

docs-web/pom.xml
docs-web/src/main/java/com/sismics/docs/rest/resource/FileResource.java
docs-web/src/main/webapp/src/app/docs/controller/settings/SettingsWorkflowEdit.js
docs-web/src/main/webapp/src/partial/docs/settings.workflow.edit.html
docs-web/src/main/webapp/src/style/main.less

required to successfully compile Sismics Docs with JDK 11

Open jdk11

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

Closes https://github.com/sismics/docs/issues/265

Added OCR support for Dutch (Nederlands)

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

Turkish Language Support Added

Turkish Language Support

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

Hello I have added hebrew support by following the exact files mentioned here:
https://github.com/vasilevich/docs/commit/7b2bd6f9ebfedb844977dbb009b082d52f87fe7d#diff-e49416f989f7fe8e14cae2493776453b
according to my enhancement request here:
https://github.com/sismics/docs/issues/319
thank you!

Hebrew Language Support

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

First time doing pull request. Let me know if I'm doing something wrong.
Thanks.

Add Hungarian Language Support

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

OCR support for Finnish (Suomi) and Swedish (Svenska) languages.
Thanks for the great project!

Finnish and Swedish Language Support

---

.travis.yml
Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

OCR support for Latvian (Latviešu) language.

Latvian Language Support

---

docs-importer/Dockerfile
docs-importer/README.md
docs-importer/env.sh
docs-importer/main.js
docs-importer/package-lock.json
docs-importer/package.json
docs-importer/pref

Improves on #362 . Added ability to import tags from the filename given by `#`, choose a language for the document and made a Docker container which can be configured with environment variables.

Improve the file importer

---

docs-importer/Dockerfile
docs-importer/README.md
docs-importer/env.sh
docs-importer/main.js
docs-importer/pref

Added option to copy a file before it is deleted after being imported following @Cornelicorn 's recommendations.

Added option to copy a file before it is deleted after being imported

---

docs-web/src/main/java/com/sismics/docs/rest/resource/RouteResource.java
docs-web/src/test/java/com/sismics/docs/rest/TestRouteResource.java

This should close #421. Feedback and comments are welcome.

Fixed sending workflow emails to previous assignee

---

docs-web/src/main/webapp/src/locale/it.json

Hi, this refers #456 . If it will be merged can you please mark this PR with the `hacktoberfest-accepted` label? Thank you.

Added italian translation

---

README.md
docs-core/pom.xml
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-core/src/main/java/com/sismics/docs/core/dao/UserDao.java
docs-core/src/main/resources/db/update/dbupdate-000-0.sql

- Since I did not find the available environment variables when I tried to setup the application I thought it might be helpful for others if they were included inside the README.
- Additionally I added two basic examples for usage with docker-compose

Adjust bcrypt and improve readme

---

docs-importer/Dockerfile

Is correctly set in configuration dialogue but not in docker vars

Fix importer default file filter (#486)

---

docs-web/src/main/webapp/src/locale/de.json

Fix de.json

---

docs-web/src/main/webapp/src/locale/de.json

* plural forms
* spelling of composed words
* spaces between numbers and measurement units
* typographic ellipsis (\u2026) instead of three dots

proofread German translation

---

.github/workflows/build-deploy.yml

Fixes #541
Begin using GitHub Actions for CI/CD.

GitHub Actions CI/CD workflow

---

Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js

Would it be possible to add also czech language support for tesseract?
Thank you in advanced.

Add OCR support for Czech language

---

docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
docs-core/src/main/java/com/sismics/docs/core/dao/FileDao.java
docs-web-common/src/test/java/com/sismics/docs/rest/BaseJerseyTest.java
docs-web-common/src/test/java/com/sismics/docs/rest/util/ClientUtil.java
docs-web/src/main/java/com/sismics/docs/rest/resource/BaseResource.java
docs-web/src/main/java/com/sismics/docs/rest/resource/DocsMessageBodyWriter.java
docs-web/src/main/java/com/sismics/docs/rest/resource/FileResource.java
docs-web/src/test/java/com/sismics/docs/rest/TestAuditLogResource.java
docs-web/src/test/java/com/sismics/docs/rest/TestDocumentResource.java
docs-web/src/test/java/com/sismics/docs/rest/TestFileResource.java

This is a draft for https://github.com/sismics/docs/issues/570 , can you tell me if you have feedbacks before I finish it?

Download zip of files not in same document

---

docs-web/src/main/webapp/src/locale/en.json

en.json: minor grammar corrections

docs-web/src/main/webapp/src/locale/en.json: minor grammar corrections

---

docs-core/src/main/java/com/sismics/docs/core/constant/ConfigType.java
docs-core/src/main/java/com/sismics/docs/core/util/authentication/LdapAuthenticationHandler.java
docs-web/src/main/java/com/sismics/docs/rest/resource/AppResource.java
docs-web/src/main/webapp/src/locale/de.json
docs-web/src/main/webapp/src/locale/en.json
docs-web/src/main/webapp/src/partial/docs/settings.ldap.html

sorry, made a new PR for the same stuff

support ldaps

---

docs-web/src/main/webapp/src/share.html

Fix bug https://github.com/sismics/docs/issues/580

Fix no favicon on shares

---

Dockerfile
docs-core/src/main/java/com/sismics/docs/core/constant/Constants.java
docs-web/src/main/webapp/src/app/docs/app.js
docs-web/src/main/webapp/src/app/share/app.js
docs-web/src/main/webapp/src/index.html
docs-web/src/main/webapp/src/locale/angular-locale_sq_AL.js
docs-web/src/main/webapp/src/locale/sq_AL.json

Added support for Albanian language (shqip).

Albanian Language Support

---

docs-core/pom.xml
docs-core/src/main/java/com/sismics/util/jpa/EMF.java
pom.xml

Noticed the version was old because of the name of the PostgreSQL dialect, the API change is very limited

Upgrade Hibernate version

---

docs-web/src/test/java/com/sismics/docs/rest/TestUserResource.java

this fixes a test adding up to the previously merged #731

fix unit test

---

docs-core/pom.xml
docs-core/src/main/java/com/sismics/docs/core/util/authentication/LdapAuthenticationHandler.java
docs-web/pom.xml
docs-web/src/test/java/com/sismics/docs/rest/TestAppResource.java
pom.xml

needed for Active Directory, fixes #734

add explicit binding
